### ISSUE TITLE
Crash on minimizing kodiki on Windows

### ISSUE THREAD

**Issue by gavlig** [gavlig/kodiki#5]
thread 'Compute Task Pool (0)' panicked at C:\Users\gavlig\.cargo\registry\src\index.crates.io-6f17d22bba15001f\parry3d-0.13.5\src\query\clip\clip_aabb_line.rs:141:19:
Matrix index out of bounds.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (0)' panicked at C:\Users\gavlig\.cargo\git\checkouts\bevy-7d8a25fd14ce7172\b2e0894\crates\bevy_ecs\src\schedule\executor\multi_threaded.rs:459:45:
internal error: entered unreachable code: sending into a closed channel
thread 'Compute Task Pool (0)' panicked at C:\Users\gavlig\.cargo\git\checkouts\bevy-7d8a25fd14ce7172\b2e0894\crates\bevy_ecs\src\schedule\executor\multi_threaded.rs:459:45:
internal error: entered unreachable code: sending into a closed channel
thread 'Compute Task Pool (0)' panicked at C:\Users\gavlig\.cargo\git\checkouts\bevy-7d8a25fd14ce7172\b2e0894\crates\bevy_ecs\src\schedule\executor\multi_threaded.rs:194:60:
A system has panicked so the executor cannot continue.: RecvError

**Comment by gavlig** [comment]
Fixed in 9324ca868efc0b87e1f65fe5d2df4692eb555040 and [e11d34](https://github.com/gavlig/parry/commit/e11d34f26f85914096cdcba4611e25530ff835c1) for binaries with fix see [release 0.11](https://github.com/gavlig/kodiki/releases/tag/0.11)
